# Generated by Django 5.2.5 on 2025-11-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reorder_level',
        ),
        migrations.AddField(
            model_name='employee',
            name='nic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
