# Generated by Django 5.2.5 on 2025-12-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_email_remove_product_reorder_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vehicle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
