# Generated by Django 5.2.5 on 2025-12-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
