# Generated by Django 5.2.5 on 2025-12-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sale_vehicle_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hide_bill_threshold', models.DecimalField(decimal_places=2, default=2000.0, max_digits=12)),
                ('require_admin_approval', models.BooleanField(default=True)),
                ('enable_audit_logging', models.BooleanField(default=True)),
                ('staff_can_edit_stock_only', models.BooleanField(default=True)),
                ('show_cost_to_staff', models.BooleanField(default=False)),
                ('auto_backup_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
    ]
