# Generated by Django 5.2.5 on 2025-12-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
